markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Lo√Øc's Blog
url: http://loicdescotte.github.io
description: A blog about Scala, Java and other coding stuffs
twitter: loic_d